// SPDX-License-Identifier: GPL-3.0-or-later

//! Hayes-compatible modem personality for Paula's serial port.
//!
//! [`ModemSerialSink`] implements [`crate::serial::SerialSink`] the same way
//! [`crate::serial::TcpSerialSink`] does: Paula paces every byte at the
//! SERPER rate and this sink never paces, sleeps, or blocks. It adds an AT
//! command interpreter and a TCP transport, dialed or answered, on top of
//! that contract.
//!
//! Covered: command-mode AT parsing, ATD/ATH/ATO/ATA, S-register storage
//! (including S0 auto-answer and the S1 ring counter), the `+++` escape
//! sequence, RS-232 control-line wiring (/DSR, /CTS, /CD, /DTR, /RTS), and
//! inbound calls (RING, busy-line handling for a second caller). There is
//! still no telnet NVT negotiation, no phonebook, and no AT&W persistence.
//! ATD's connect attempt also still blocks the calling thread for up to
//! five seconds; a background dial is future work.

use crate::chipset::paula::PAULA_CLOCK_HZ;
use crate::serial::SerialSink;
use std::collections::VecDeque;
use std::io::{self, Read, Write};
use std::net::{Shutdown, SocketAddr, TcpListener, TcpStream, ToSocketAddrs};
use std::sync::atomic::{AtomicBool, AtomicIsize, Ordering};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::Duration;

/// Longest command line a real Hayes modem accepts before giving up; a line
/// that grows past this without a terminating CR is discarded rather than
/// grown without bound.
const MAX_LINE_LEN: usize = 255;

/// Cap on modem-generated bytes (echo plus result-code text) waiting for the
/// guest to read them. Unlike [`crate::serial::CHANNEL_OUTPUT_CAPACITY`]
/// this queue only ever holds short protocol strings ("\r\nOK\r\n" and
/// friends) between guest reads, so the cap is never expected to bind in
/// practice; it exists only so a guest that stops reading altogether cannot
/// make this queue grow forever.
const OUT_QUEUE_CAPACITY: usize = 4096;

/// Errors ATD reports as distinct result codes: a refused connection is
/// BUSY, anything else NO CARRIER.
#[derive(Debug)]
pub(crate) enum DialError {
    Refused,
    Unreachable,
}

/// Construction-time options for [`ModemSerialSink::new_tcp`] -- what the
/// host configuration decides once, as opposed to AT-settable state a guest
/// program controls at runtime.
#[derive(Default, Clone)]
pub struct ModemOptions {
    /// Bind and answer inbound calls on "host:port". `None`: dial-out only,
    /// same as milestone M1 -- nothing ever RINGs, ATA always reports NO
    /// CARRIER.
    pub listen: Option<String>,
}

/// The byte transport a [`ModemSerialSink`] dials out on. Abstracted so the
/// state machine can be exercised in tests without opening real sockets;
/// [`TcpModemTransport`] is the production implementation.
pub(crate) trait ModemTransport: Send {
    /// Dial `host_port` ("host:port"). Synchronous, startup-connect style:
    /// blocks the calling thread until the connection succeeds or fails.
    fn dial(&mut self, host_port: &str) -> Result<(), DialError>;
    /// Bytes the far end has sent; `None` when none are available right now
    /// (this does not by itself mean the connection is down -- callers
    /// cross-check [`ModemTransport::carrier`] for that).
    fn read_byte(&mut self) -> Option<u8>;
    /// Cheap, non-blocking probe: would `read_byte` return data right now?
    fn has_pending(&self) -> bool;
    fn write_byte(&mut self, b: u8);
    /// Whether a carrier is currently up (connected).
    fn carrier(&self) -> bool;
    /// Idempotent: drop the connection if one is up.
    fn hangup(&mut self);
    /// Accept incoming calls on `addr` ("host:port"). Replaces any previous
    /// listener.
    fn listen(&mut self, addr: &str) -> io::Result<()>;
    /// An inbound caller is waiting, unanswered.
    fn ringing(&self) -> bool;
    /// Promote the waiting caller to the live connection. False when none
    /// is waiting (nobody is calling, or the caller hung up before being
    /// answered).
    fn answer(&mut self) -> bool;
    /// Drop the waiting caller without answering.
    fn reject(&mut self);
}

/// Spawn the background reader shared by every connected/accepted
/// [`TcpModemTransport`] state: pushes bytes into `tx` and bumps `buffered`
/// so the owning transport's `has_pending` stays a cheap atomic load, then
/// clears `writer` and `carrier` on EOF or error so the owner's next probe
/// sees the connection is gone.
fn spawn_modem_reader(
    mut stream: TcpStream,
    tx: std::sync::mpsc::Sender<u8>,
    buffered: Arc<AtomicIsize>,
    writer: Arc<Mutex<Option<TcpStream>>>,
    carrier: Arc<AtomicBool>,
) -> io::Result<()> {
    thread::Builder::new()
        .name("modem-tcp".into())
        .spawn(move || {
            let mut buf = [0u8; 512];
            loop {
                match stream.read(&mut buf) {
                    Ok(0) | Err(_) => break,
                    Ok(n) => {
                        for &b in &buf[..n] {
                            if tx.send(b).is_err() {
                                return;
                            }
                            buffered.fetch_add(1, Ordering::Release);
                        }
                    }
                }
            }
            *writer.lock().unwrap() = None;
            carrier.store(false, Ordering::Release);
        })?;
    Ok(())
}

/// The modem's real transport: dials out over TCP, reusing
/// [`crate::serial::TcpSerialSink`]'s reader-thread-plus-atomic-counter
/// pattern so Paula's idle fast path never touches a socket.
pub(crate) struct TcpModemTransport {
    rx: Option<std::sync::mpsc::Receiver<u8>>,
    /// Write half of the live connection, `None` when nothing is connected.
    /// Cleared by [`spawn_modem_reader`] on disconnect and by
    /// [`TcpModemTransport::write_byte`] on a failed write, mirroring
    /// `TcpSerialSink`.
    writer: Arc<Mutex<Option<TcpStream>>>,
    /// Bytes staged in `rx`; signed for the same transient-debt reason as
    /// `TcpSerialSink::buffered` (a `read_byte` racing ahead of the reader
    /// thread's `fetch_add` dips to -1 rather than wrapping huge).
    buffered: Arc<AtomicIsize>,
    /// Mirrors "the writer slot is occupied", kept as its own flag so
    /// `carrier()` is a plain atomic load rather than a mutex lock on
    /// Paula-facing hot paths (`control_lines`, `has_pending_input`).
    carrier: Arc<AtomicBool>,
    /// Inbound connection accepted by the `listen()` thread and parked here
    /// until `answer()` promotes it or `reject()` drops it. `None` when
    /// nobody is calling in.
    pending: Arc<Mutex<Option<TcpStream>>>,
    /// Mirrors "`pending` is occupied", kept as its own flag for the same
    /// atomic-load-only reason as `carrier`: `ringing()` is on the same
    /// Paula-facing footing as `carrier()`.
    ringing: Arc<AtomicBool>,
    /// The address `listen()` actually bound (a port of 0 resolves here).
    /// Test-only accessor, mirroring `TcpSerialSink::local_addr`.
    listen_addr: Option<SocketAddr>,
}

impl TcpModemTransport {
    /// A transport with nothing connected yet -- the emulator's
    /// dial-on-demand starting state.
    pub(crate) fn new() -> Self {
        Self {
            rx: None,
            writer: Arc::new(Mutex::new(None)),
            buffered: Arc::new(AtomicIsize::new(0)),
            carrier: Arc::new(AtomicBool::new(false)),
            pending: Arc::new(Mutex::new(None)),
            ringing: Arc::new(AtomicBool::new(false)),
            listen_addr: None,
        }
    }

    /// The address [`ModemTransport::listen`] actually bound. Test-only:
    /// production callers pass an explicit port (or accept the default),
    /// only tests bind port 0 and need to learn what they got.
    #[cfg_attr(not(test), allow(dead_code))]
    pub(crate) fn listen_addr(&self) -> Option<SocketAddr> {
        self.listen_addr
    }
}

impl ModemTransport for TcpModemTransport {
    fn dial(&mut self, host_port: &str) -> Result<(), DialError> {
        let addr = host_port
            .to_socket_addrs()
            .ok()
            .and_then(|mut it| it.next());
        let connect_result = match addr {
            Some(a) => TcpStream::connect_timeout(&a, Duration::from_secs(5)),
            None => TcpStream::connect(host_port),
        };
        let stream = connect_result.map_err(|e| match e.kind() {
            io::ErrorKind::ConnectionRefused => DialError::Refused,
            _ => DialError::Unreachable,
        })?;
        let _ = stream.set_nodelay(true);
        let writer_clone = stream.try_clone().map_err(|_| DialError::Unreachable)?;
        let (tx, rx) = std::sync::mpsc::channel();
        *self.writer.lock().unwrap() = Some(writer_clone);
        self.carrier.store(true, Ordering::Release);
        self.rx = Some(rx);
        spawn_modem_reader(
            stream,
            tx,
            Arc::clone(&self.buffered),
            Arc::clone(&self.writer),
            Arc::clone(&self.carrier),
        )
        .map_err(|_| DialError::Unreachable)?;
        Ok(())
    }

    fn read_byte(&mut self) -> Option<u8> {
        let b = self.rx.as_ref()?.try_recv().ok();
        if b.is_some() {
            self.buffered.fetch_sub(1, Ordering::Release);
        }
        b
    }

    fn has_pending(&self) -> bool {
        self.buffered.load(Ordering::Acquire) > 0
    }

    fn write_byte(&mut self, b: u8) {
        let mut guard = self.writer.lock().unwrap();
        if let Some(w) = guard.as_mut() {
            if w.write_all(&[b]).is_err() {
                *guard = None;
                drop(guard);
                self.carrier.store(false, Ordering::Release);
            }
        }
    }

    fn carrier(&self) -> bool {
        self.carrier.load(Ordering::Acquire)
    }

    fn hangup(&mut self) {
        if let Some(stream) = self.writer.lock().unwrap().take() {
            let _ = stream.shutdown(Shutdown::Both);
        }
        self.carrier.store(false, Ordering::Release);
    }

    fn listen(&mut self, addr: &str) -> io::Result<()> {
        let listener = TcpListener::bind(addr)?;
        let local_addr = listener.local_addr()?;
        let pending = Arc::new(Mutex::new(None));
        let ringing = Arc::new(AtomicBool::new(false));
        let (accept_pending, accept_ringing, accept_carrier) = (
            Arc::clone(&pending),
            Arc::clone(&ringing),
            Arc::clone(&self.carrier),
        );
        thread::Builder::new()
            .name("modem-tcp-listen".into())
            .spawn(move || {
                loop {
                    let Ok((stream, _peer)) = listener.accept() else {
                        return;
                    };
                    // The phone-line-busy analogue: a call is live, or an
                    // earlier caller is still parked unanswered, so this
                    // one gets connection-then-close -- the fast-busy tone
                    // an auto-dialer reads as BUSY, never a ring.
                    if accept_carrier.load(Ordering::Acquire)
                        || accept_ringing.load(Ordering::Acquire)
                    {
                        drop(stream);
                        continue;
                    }
                    let _ = stream.set_nodelay(true);
                    *accept_pending.lock().unwrap() = Some(stream);
                    accept_ringing.store(true, Ordering::Release);
                }
            })?;
        // Replaces whatever `listen()` bound before: a previous listener
        // thread (if any) is left running against its own now-orphaned
        // `pending`/`ringing`, harmless since nothing reads them anymore.
        self.pending = pending;
        self.ringing = ringing;
        self.listen_addr = Some(local_addr);
        Ok(())
    }

    fn ringing(&self) -> bool {
        self.ringing.load(Ordering::Acquire)
    }

    fn answer(&mut self) -> bool {
        let Some(stream) = self.pending.lock().unwrap().take() else {
            return false;
        };
        self.ringing.store(false, Ordering::Release);
        // A caller that hung up while waiting leaves a closed socket
        // parked; a zero-length peek reads EOF without consuming any real
        // data, so a dead parked stream is caught here instead of handing
        // the guest a CONNECT that drops on the next byte.
        let _ = stream.set_nonblocking(true);
        let mut probe = [0u8; 1];
        let dead = matches!(stream.peek(&mut probe), Ok(0));
        let _ = stream.set_nonblocking(false);
        if dead {
            return false;
        }
        let Ok(clone) = stream.try_clone() else {
            return false;
        };
        let (tx, rx) = std::sync::mpsc::channel();
        *self.writer.lock().unwrap() = Some(clone);
        self.rx = Some(rx);
        self.carrier.store(true, Ordering::Release);
        if spawn_modem_reader(
            stream,
            tx,
            Arc::clone(&self.buffered),
            Arc::clone(&self.writer),
            Arc::clone(&self.carrier),
        )
        .is_err()
        {
            *self.writer.lock().unwrap() = None;
            self.carrier.store(false, Ordering::Release);
            return false;
        }
        true
    }

    fn reject(&mut self) {
        if let Some(stream) = self.pending.lock().unwrap().take() {
            let _ = stream.shutdown(Shutdown::Both);
        }
        self.ringing.store(false, Ordering::Release);
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Mode {
    Command,
    Online,
}

/// A withheld `+++` escape candidate mid-flight. See
/// [`ModemSerialSink::handle_online_byte`] for the full state machine; kept
/// this small (a count and one timestamp) because all withheld bytes are
/// the same S2 character, so there is nothing else to remember.
#[derive(Clone, Copy)]
struct Escape {
    /// Escape characters accepted so far, 1..=3.
    count: u8,
    /// `at_cck` of the most recently accepted escape character.
    last_cck: u64,
    /// `count` has reached 3 and we are waiting out the trailing guard.
    awaiting_trail: bool,
}

#[derive(Clone, Copy)]
struct Settings {
    /// ATEn: echo guest command-mode bytes back to the guest.
    echo: bool,
    /// ATVn: verbose ("\r\nOK\r\n") vs numeric ("0\r") result codes.
    verbose: bool,
    /// ATQn: suppress all result codes.
    quiet: bool,
    /// S0: rings to wait through before auto-answering an inbound call; 0
    /// (default) disables auto-answer, ATA is then the only way to answer.
    s0: u8,
    /// S2: the `+++` escape character.
    s2: u8,
    /// S12: escape guard time, in fiftieths of a second.
    s12: u8,
    /// AT&Cn: n=0 means /CD reports asserted regardless of carrier state
    /// ("DCD always"); the default (n=1) tracks the real carrier.
    dcd_always: bool,
    /// AT&Dn: only 2 (default) and 3 are modeled -- both hang up on a
    /// DTR true->false transition. 0 and 1 are accepted but ignored (no
    /// auto-answer to disable, and &D1's escape-to-command-without-hangup
    /// behaviour is not modeled).
    dtr_action: u8,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            echo: true,
            verbose: true,
            quiet: false,
            s0: 0,
            s2: b'+',
            s12: 50,
            dcd_always: false,
            dtr_action: 2,
        }
    }
}

enum ResultCode {
    Ok,
    Connect,
    NoCarrier,
    Error,
    Busy,
}

/// A Hayes-compatible modem sitting on Paula's serial port. Paula paces all
/// bytes at the SERPER rate through [`crate::serial::SerialSink::write_byte`]
/// / `read_byte`; this sink never paces, sleeps, or blocks -- the dial
/// transport does its own I/O on a background thread (see
/// [`TcpModemTransport`]).
pub struct ModemSerialSink {
    transport: Box<dyn ModemTransport>,
    mode: Mode,
    /// Command-mode line buffer, capped at [`MAX_LINE_LEN`].
    line: Vec<u8>,
    settings: Settings,
    /// Last rate reported via [`crate::serial::SerialSink::baud_changed`],
    /// quoted back in the CONNECT text.
    last_baud: Option<u32>,
    /// Modem-generated bytes (echo, result codes) waiting for the guest.
    out_queue: VecDeque<u8>,
    /// In-progress `+++` escape candidate, if any. Only meaningful while
    /// `mode` is `Online`.
    escape: Option<Escape>,
    /// `at_cck` of the most recent guest activity while online (an ordinary
    /// forwarded byte, an escape character, or the CONNECT that entered
    /// online mode) -- the reference point a new escape candidate's lead
    /// guard is measured from.
    last_online_activity_cck: Option<u64>,
    /// Previous DTR level, to detect a true->false transition in
    /// [`crate::serial::SerialSink::set_control_outputs`]. `None` until the
    /// first call, so the very first report (whatever it says) is never
    /// itself treated as a drop.
    dtr_prev: Option<bool>,
    /// A call is up (dialed, answered, or parked in command mode behind a
    /// `+++` escape with the line still connected) and this sink has not
    /// yet told the guest it dropped. Set on every transition into
    /// [`ModemSerialSink::enter_online`], cleared the moment NO CARRIER is
    /// reported for it (by [`SerialSink::poll`] catching a silent drop in
    /// command mode, by the online-mode remote-close path in
    /// [`SerialSink::read_byte`], or by [`ModemSerialSink::hangup_internal`]
    /// ending the call locally).
    carrier_expected: bool,
    /// S1: rings answered by RING since the last decay or hangup, readable
    /// and writable via ATS1. Real Hayes modems drift it back to 0 eight
    /// seconds after the last ring even with no call resolved either way;
    /// [`ModemSerialSink::poll`] applies that decay from `last_ring_cck`.
    s1: u8,
    /// `at_cck` of the most recently sent RING, `None` when nothing is
    /// currently ringing and S1 has already decayed. The reference point
    /// for both the ring cadence and the S1 decay timer.
    last_ring_cck: Option<u64>,
}

impl ModemSerialSink {
    /// The emulator's constructor: dial is always on-demand via ATD;
    /// `options.listen` additionally binds an answering side at startup, so
    /// inbound calls can RING and be picked up (ATA, or S0 auto-answer).
    /// Propagates a bind failure with `?`, the same convention
    /// [`crate::serial::TcpSerialSink::listen`] uses -- a modem that was
    /// asked to answer calls and silently cannot is worse than a config
    /// error at startup.
    pub fn new_tcp(options: ModemOptions) -> anyhow::Result<Self> {
        let mut transport = TcpModemTransport::new();
        if let Some(addr) = options.listen.as_deref() {
            transport.listen(addr)?;
        }
        Ok(Self::with_transport(Box::new(transport)))
    }

    pub(crate) fn with_transport(transport: Box<dyn ModemTransport>) -> Self {
        Self {
            transport,
            mode: Mode::Command,
            line: Vec::new(),
            settings: Settings::default(),
            last_baud: None,
            out_queue: VecDeque::new(),
            escape: None,
            last_online_activity_cck: None,
            dtr_prev: None,
            carrier_expected: false,
            s1: 0,
            last_ring_cck: None,
        }
    }

    fn queue_out_byte(&mut self, b: u8) {
        if self.out_queue.len() == OUT_QUEUE_CAPACITY {
            self.out_queue.pop_front();
        }
        self.out_queue.push_back(b);
    }

    fn queue_result(&mut self, code: ResultCode) {
        if self.settings.quiet {
            return;
        }
        let bytes = if self.settings.verbose {
            let s = match code {
                ResultCode::Ok => "OK".to_string(),
                ResultCode::Connect => match self.last_baud {
                    Some(bps) => format!("CONNECT {bps}"),
                    None => "CONNECT".to_string(),
                },
                ResultCode::NoCarrier => "NO CARRIER".to_string(),
                ResultCode::Error => "ERROR".to_string(),
                ResultCode::Busy => "BUSY".to_string(),
            };
            format!("\r\n{s}\r\n").into_bytes()
        } else {
            let n = match code {
                ResultCode::Ok => "0",
                ResultCode::Connect => "1",
                ResultCode::NoCarrier => "3",
                ResultCode::Error => "4",
                ResultCode::Busy => "7",
            };
            format!("{n}\r").into_bytes()
        };
        for b in bytes {
            self.queue_out_byte(b);
        }
    }

    fn queue_identity(&mut self) {
        // ATIn: an identity banner. Real modems vary it by n; M1 has no
        // product line to differentiate, so every digit gets the same
        // short string. Not a "result code", so not gated by ATQ1.
        for b in "\r\nCopperline modem\r\n".bytes() {
            self.queue_out_byte(b);
        }
    }

    fn queue_s_read(&mut self, reg: u8) {
        let val = match reg {
            0 => self.settings.s0,
            1 => self.s1,
            2 => self.settings.s2,
            12 => self.settings.s12,
            _ => 0,
        };
        for b in format!("\r\n{val}\r\n").into_bytes() {
            self.queue_out_byte(b);
        }
    }

    fn set_s_register(&mut self, reg: u8, val: u8) {
        match reg {
            0 => self.settings.s0 = val,
            1 => self.s1 = val,
            2 => self.settings.s2 = val,
            12 => self.settings.s12 = val,
            // Every other S register is a stub: no state, no error, just an
            // accepted write (real modems have dozens few programs touch).
            _ => {}
        }
    }

    fn reset_defaults(&mut self) {
        self.settings = Settings::default();
    }

    /// Idempotent hangup: drops the transport connection and, if a call was
    /// in progress, returns to command mode. Shared by ATH, ATZ/AT&F, and a
    /// DTR-drop with AT&D2/3. Also the one place S1/ring state resets on
    /// "the call is over", per Hayes convention (the other is the 8-second
    /// decay in [`ModemSerialSink::poll`]).
    fn hangup_internal(&mut self) {
        self.transport.hangup();
        self.escape = None;
        self.mode = Mode::Command;
        self.carrier_expected = false;
        self.s1 = 0;
        self.last_ring_cck = None;
    }

    /// Guard time in color clocks: S12 is in fiftieths of a second, and one
    /// fiftieth is `PAULA_CLOCK_HZ / 50` color clocks.
    fn guard_ccks(&self) -> u64 {
        u64::from(self.settings.s12) * u64::from(PAULA_CLOCK_HZ) / 50
    }

    /// Enter online (relay) mode after a successful ATD, an answered
    /// inbound call (ATA or S0 auto-answer), or an ATO with carrier up.
    /// `at_cck` becomes the escape lead-guard's reference point -- an
    /// escape cannot start until S12 of silence has passed since.
    fn enter_online(&mut self, at_cck: u64) {
        self.mode = Mode::Online;
        self.escape = None;
        self.last_online_activity_cck = Some(at_cck);
        self.carrier_expected = true;
        self.s1 = 0;
        self.last_ring_cck = None;
        self.queue_result(ResultCode::Connect);
    }

    fn do_dial(&mut self, target: &[u8], at_cck: u64) {
        if self.transport.carrier() {
            // A guest that escaped to command mode with a call still up
            // and then dials again means "hang up and place a new call" --
            // the old line does not stay parked in the background while a
            // second one is placed.
            self.transport.hangup();
        }
        let target = String::from_utf8_lossy(target);
        let target = target.trim();
        let host_port = if target.contains(':') {
            target.to_string()
        } else {
            format!("{target}:23")
        };
        match self.transport.dial(&host_port) {
            Ok(()) => self.enter_online(at_cck),
            Err(DialError::Refused) => self.queue_result(ResultCode::Busy),
            Err(DialError::Unreachable) => self.queue_result(ResultCode::NoCarrier),
        }
    }

    fn do_answer(&mut self, at_cck: u64) {
        if self.transport.carrier() {
            // Same reasoning as `do_dial`: answering while a call is
            // already up drops it first rather than leaving it parked.
            self.transport.hangup();
        }
        if self.transport.answer() {
            self.enter_online(at_cck);
        } else {
            self.queue_result(ResultCode::NoCarrier);
        }
    }

    /// Ring cadence and RING/S0/S1 bookkeeping, driven by [`Self::poll`].
    /// Real Hayes modems ring roughly every four seconds of line time and
    /// give S1 the same eight-second decay a real line's ring-counter
    /// register carries between calls.
    fn poll_ring(&mut self, at_cck: u64) {
        const RING_CADENCE_CCKS: u64 = 4 * PAULA_CLOCK_HZ as u64;
        const S1_DECAY_CCKS: u64 = 8 * PAULA_CLOCK_HZ as u64;
        const RING_ABANDON_COUNT: u8 = 10;

        if self.mode == Mode::Command && self.transport.ringing() {
            let due = match self.last_ring_cck {
                None => true,
                Some(last) => at_cck.saturating_sub(last) >= RING_CADENCE_CCKS,
            };
            if due {
                self.queue_ring();
                self.last_ring_cck = Some(at_cck);
                self.s1 = self.s1.saturating_add(1);
                if self.s1 >= RING_ABANDON_COUNT {
                    // The exchange gives up on a call nobody picked up,
                    // same as a real line timing out an unanswered ring.
                    self.transport.reject();
                } else if self.settings.s0 > 0 && self.s1 >= self.settings.s0 {
                    self.do_answer(at_cck);
                }
            }
        }
        // S1 drifts back to 0 eight seconds after the last ring whether or
        // not that call was ever picked up.
        if let Some(last) = self.last_ring_cck {
            if at_cck.saturating_sub(last) >= S1_DECAY_CCKS {
                self.s1 = 0;
                self.last_ring_cck = None;
            }
        }
    }

    fn queue_ring(&mut self) {
        if self.settings.quiet {
            return;
        }
        let bytes: &[u8] = if self.settings.verbose {
            b"\r\nRING\r\n"
        } else {
            b"2\r"
        };
        for &b in bytes {
            self.queue_out_byte(b);
        }
    }

    /// Parse and execute one complete AT command line (without the
    /// terminating CR). Hayes chains commands left to right on one line
    /// (`ATE0V1` is legal), so this walks the bytes after the "AT" prefix
    /// once, dispatching each recognized letter in turn. The first
    /// malformed command aborts the rest of the line with ERROR, matching
    /// real Hayes behaviour.
    fn execute_line(&mut self, line: &[u8], at_cck: u64) {
        if line.is_empty() {
            // A bare CR in command mode gets no response.
            return;
        }
        let text = String::from_utf8_lossy(line);
        let upper = text.to_ascii_uppercase();
        let Some(rest) = upper.strip_prefix("AT") else {
            self.queue_result(ResultCode::Error);
            return;
        };
        let bytes = rest.as_bytes();
        let mut i = 0;
        // Set when a command already queued its own terminal result
        // (CONNECT/BUSY/NO CARRIER from D/O), so the line doesn't also get
        // a trailing OK.
        let mut terminal_result = false;
        while i < bytes.len() {
            match bytes[i] as char {
                'E' => {
                    let (v, ni) = read_digit_default(bytes, i + 1, 0);
                    self.settings.echo = v != 0;
                    i = ni;
                }
                'Q' => {
                    let (v, ni) = read_digit_default(bytes, i + 1, 0);
                    self.settings.quiet = v != 0;
                    i = ni;
                }
                'V' => {
                    let (v, ni) = read_digit_default(bytes, i + 1, 0);
                    self.settings.verbose = v != 0;
                    i = ni;
                }
                'Z' => {
                    let (_v, ni) = read_digit_default(bytes, i + 1, 0);
                    self.reset_defaults();
                    self.hangup_internal();
                    i = ni;
                }
                'H' => {
                    let (_v, ni) = read_digit_default(bytes, i + 1, 0);
                    self.hangup_internal();
                    i = ni;
                }
                'O' => {
                    let (_v, ni) = read_digit_default(bytes, i + 1, 0);
                    if self.transport.carrier() {
                        self.enter_online(at_cck);
                    } else {
                        self.queue_result(ResultCode::NoCarrier);
                    }
                    terminal_result = true;
                    i = ni;
                }
                'I' => {
                    let (_v, ni) = read_digit_default(bytes, i + 1, 0);
                    self.queue_identity();
                    i = ni;
                }
                'A' => {
                    self.do_answer(at_cck);
                    terminal_result = true;
                    i += 1;
                }
                'D' => {
                    let mut j = i + 1;
                    if j < bytes.len() && matches!(bytes[j] as char, 'T' | 'P') {
                        j += 1;
                    }
                    let target = &bytes[j..];
                    self.do_dial(target, at_cck);
                    terminal_result = true;
                    i = bytes.len();
                }
                '&' => {
                    if i + 1 >= bytes.len() {
                        self.queue_result(ResultCode::Error);
                        return;
                    }
                    match bytes[i + 1] as char {
                        'F' => {
                            self.reset_defaults();
                            self.hangup_internal();
                            i += 2;
                        }
                        'C' => {
                            let (v, ni) = read_digit_default(bytes, i + 2, 1);
                            self.settings.dcd_always = v == 0;
                            i = ni;
                        }
                        'D' => {
                            let (v, ni) = read_digit_default(bytes, i + 2, 2);
                            self.settings.dtr_action = v;
                            i = ni;
                        }
                        _ => {
                            self.queue_result(ResultCode::Error);
                            return;
                        }
                    }
                }
                'S' => {
                    let start = i + 1;
                    let mut j = start;
                    while j < bytes.len() && bytes[j].is_ascii_digit() {
                        j += 1;
                    }
                    if j == start {
                        self.queue_result(ResultCode::Error);
                        return;
                    }
                    let reg: u8 = std::str::from_utf8(&bytes[start..j])
                        .unwrap()
                        .parse()
                        .unwrap_or(0);
                    if j < bytes.len() && bytes[j] as char == '?' {
                        self.queue_s_read(reg);
                        i = j + 1;
                    } else if j < bytes.len() && bytes[j] as char == '=' {
                        let vstart = j + 1;
                        let mut k = vstart;
                        while k < bytes.len() && bytes[k].is_ascii_digit() {
                            k += 1;
                        }
                        if k == vstart {
                            self.queue_result(ResultCode::Error);
                            return;
                        }
                        let val: u8 = std::str::from_utf8(&bytes[vstart..k])
                            .unwrap()
                            .parse()
                            .unwrap_or(0);
                        self.set_s_register(reg, val);
                        i = k;
                    } else {
                        self.queue_result(ResultCode::Error);
                        return;
                    }
                }
                _ => {
                    self.queue_result(ResultCode::Error);
                    return;
                }
            }
        }
        if !terminal_result {
            self.queue_result(ResultCode::Ok);
        }
    }

    fn command_mode_write(&mut self, b: u8, at_cck: u64) {
        if self.settings.echo {
            self.queue_out_byte(b);
        }
        if b == 0x0D {
            let line = std::mem::take(&mut self.line);
            self.execute_line(&line, at_cck);
            return;
        }
        if self.line.len() >= MAX_LINE_LEN {
            self.line.clear();
            self.queue_result(ResultCode::Error);
            return;
        }
        self.line.push(b);
    }

    fn forward_escape_chars(&mut self, count: u8) {
        for _ in 0..count {
            self.transport.write_byte(self.settings.s2);
        }
    }

    /// The `+++` escape state machine. Deterministic and `at_cck`-only --
    /// never host time. Hayes semantics: at least S12 of guest silence,
    /// then exactly three S2 characters each within S12 of the previous,
    /// then S12 of guest silence with nothing else sent drops to command
    /// mode (carrier stays up; ATO returns online) and reports OK. Anything
    /// else -- a non-escape byte, a fourth escape char, or a gap violating
    /// either window -- forwards the withheld escape characters plus the
    /// offending byte and the relay continues.
    ///
    /// The trailing guard is normally completed by [`Self::poll`], which is
    /// driven purely by elapsed `at_cck` and needs no further guest byte to
    /// notice the guard has expired -- a guest that falls silent right
    /// after `+++` still drops to command mode on schedule. This method's
    /// own `awaiting_trail` branch stays as a same-call fallback for direct
    /// callers that drive `write_byte` without ever calling `poll` (this
    /// module's own unit tests): a guest byte landing after the guard has
    /// elapsed is itself treated as the first character of a new command
    /// line rather than being relayed.
    fn handle_online_byte(&mut self, b: u8, at_cck: u64) {
        if let Some(e) = self.escape.take() {
            let guard = self.guard_ccks();
            let gap = at_cck.saturating_sub(e.last_cck);
            if e.awaiting_trail {
                if gap >= guard {
                    self.mode = Mode::Command;
                    self.queue_result(ResultCode::Ok);
                    self.command_mode_write(b, at_cck);
                } else {
                    self.forward_escape_chars(e.count);
                    self.transport.write_byte(b);
                    self.last_online_activity_cck = Some(at_cck);
                }
                return;
            }
            if b == self.settings.s2 && gap <= guard {
                let mut e = e;
                e.count += 1;
                e.last_cck = at_cck;
                if e.count == 3 {
                    e.awaiting_trail = true;
                }
                self.escape = Some(e);
            } else if b == self.settings.s2 {
                // The withheld chars sat idle for a full guard time before
                // this byte arrived, so that silence is itself a valid lead
                // guard: this byte starts a fresh candidate rather than
                // joining (or busting) the old one.
                self.forward_escape_chars(e.count);
                self.escape = Some(Escape {
                    count: 1,
                    last_cck: at_cck,
                    awaiting_trail: false,
                });
            } else {
                self.forward_escape_chars(e.count);
                self.transport.write_byte(b);
            }
            self.last_online_activity_cck = Some(at_cck);
            return;
        }

        let guard = self.guard_ccks();
        let lead_ok = matches!(
            self.last_online_activity_cck,
            Some(prev) if at_cck.saturating_sub(prev) >= guard
        );
        if b == self.settings.s2 && lead_ok {
            self.escape = Some(Escape {
                count: 1,
                last_cck: at_cck,
                awaiting_trail: false,
            });
        } else {
            self.transport.write_byte(b);
        }
        self.last_online_activity_cck = Some(at_cck);
    }
}

/// Read an optional run of ASCII digits starting at `i`; `default` when
/// none are present. Used for the single-digit arguments to E/Q/V/H/O/I/&C/
/// &D (`ATE` alone means `ATE0`, matching common Hayes practice of treating
/// an omitted numeric argument as 0).
fn read_digit_default(bytes: &[u8], i: usize, default: u8) -> (u8, usize) {
    if i < bytes.len() && bytes[i].is_ascii_digit() {
        let start = i;
        let mut j = i;
        while j < bytes.len() && bytes[j].is_ascii_digit() {
            j += 1;
        }
        let v = std::str::from_utf8(&bytes[start..j])
            .unwrap()
            .parse()
            .unwrap_or(default);
        (v, j)
    } else {
        (default, i)
    }
}

impl SerialSink for ModemSerialSink {
    fn write_byte(&mut self, b: u8, at_cck: u64) {
        match self.mode {
            Mode::Online => self.handle_online_byte(b, at_cck),
            Mode::Command => self.command_mode_write(b, at_cck),
        }
    }

    fn read_byte(&mut self) -> Option<u8> {
        if let Some(b) = self.out_queue.pop_front() {
            return Some(b);
        }
        if self.mode == Mode::Online {
            if !self.transport.carrier() {
                // The remote end closed the connection: surface it to the
                // guest and fall back to command mode, same as a real modem
                // losing carrier mid-call.
                self.hangup_internal();
                self.queue_result(ResultCode::NoCarrier);
                return self.out_queue.pop_front();
            }
            return self.transport.read_byte();
        }
        None
    }

    fn has_pending_input(&self) -> bool {
        if !self.out_queue.is_empty() {
            return true;
        }
        if self.mode == Mode::Online {
            // A dropped carrier also counts as "pending": the next
            // `read_byte` call turns it into a queued NO CARRIER.
            return !self.transport.carrier() || self.transport.has_pending();
        }
        false
    }

    fn can_produce_input(&self) -> bool {
        true
    }

    /// Escape trailing-guard completion, a dropped-carrier NO CARRIER in
    /// command mode, and RING/S0/S1 bookkeeping -- everything this sink
    /// times off elapsed line time rather than a guest byte. See
    /// [`Self::handle_online_byte`] and [`Self::poll_ring`] for the two
    /// halves' own reasoning.
    fn poll(&mut self, at_cck: u64) {
        if self.mode == Mode::Online {
            if let Some(e) = self.escape {
                if e.awaiting_trail && at_cck.saturating_sub(e.last_cck) >= self.guard_ccks() {
                    self.mode = Mode::Command;
                    self.escape = None;
                    self.queue_result(ResultCode::Ok);
                }
            }
        }
        if self.mode == Mode::Command && self.carrier_expected && !self.transport.carrier() {
            // A call parked in command mode behind a `+++` escape whose
            // remote end drops: nothing else polls the transport while
            // idle in command mode, so without this the guest would never
            // learn the line went away short of trying ATO.
            self.carrier_expected = false;
            self.queue_result(ResultCode::NoCarrier);
        }
        self.poll_ring(at_cck);
    }

    fn reset_after_timeline_jump(&mut self) {
        // The line dropped, but the modem itself was not reset: settings
        // are retained, only the call and any in-flight state go away.
        self.transport.reject();
        self.hangup_internal();
        self.line.clear();
        self.out_queue.clear();
        self.last_online_activity_cck = None;
    }

    fn machine_reset(&mut self) {
        // A full ATZ: settings back to defaults, call dropped.
        self.reset_defaults();
        self.transport.reject();
        self.hangup_internal();
        self.line.clear();
        self.out_queue.clear();
        self.last_online_activity_cck = None;
        self.dtr_prev = None;
    }

    fn flush(&mut self) {}

    fn control_lines(&self) -> Option<u8> {
        // /DSR and /CTS are always asserted (this sink never models flow
        // control or a missing terminal). Active-low: asserted = 0 bit.
        let mut bits = 0u8;
        let cd_asserted = self.transport.carrier() || self.settings.dcd_always;
        if !cd_asserted {
            bits |= 1 << 5; // /CD deasserted -> wire high
        }
        Some(bits)
    }

    fn set_control_outputs(&mut self, dtr: bool, rts: bool) {
        let _ = rts; // accepted, unused (no hardware flow control modeled)
        let was_asserted = self.dtr_prev.replace(dtr);
        if was_asserted == Some(true) && !dtr && matches!(self.settings.dtr_action, 2 | 3) {
            self.hangup_internal();
            self.queue_result(ResultCode::NoCarrier);
        }
    }

    fn baud_changed(&mut self, bps: u32) {
        self.last_baud = Some(bps);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::Instant;

    #[derive(Default)]
    struct FakeState {
        dialed: Option<String>,
        dial_result: Option<Result<(), DialError>>,
        to_guest: VecDeque<u8>,
        from_guest: Vec<u8>,
        carrier: bool,
        hangups: u32,
        listen_addr: Option<String>,
        ringing: bool,
        reject_count: u32,
        /// A test simulating a caller who hung up before being answered:
        /// `answer()` reports failure exactly once, the same as
        /// `TcpModemTransport` catching a dead parked stream.
        pending_dead: bool,
    }

    struct FakeTransport(Arc<Mutex<FakeState>>);

    impl ModemTransport for FakeTransport {
        fn dial(&mut self, host_port: &str) -> Result<(), DialError> {
            let mut s = self.0.lock().unwrap();
            s.dialed = Some(host_port.to_string());
            match s.dial_result.take() {
                Some(Ok(())) => {
                    s.carrier = true;
                    Ok(())
                }
                Some(Err(e)) => Err(e),
                None => {
                    s.carrier = true;
                    Ok(())
                }
            }
        }

        fn read_byte(&mut self) -> Option<u8> {
            self.0.lock().unwrap().to_guest.pop_front()
        }

        fn has_pending(&self) -> bool {
            !self.0.lock().unwrap().to_guest.is_empty()
        }

        fn write_byte(&mut self, b: u8) {
            self.0.lock().unwrap().from_guest.push(b);
        }

        fn carrier(&self) -> bool {
            self.0.lock().unwrap().carrier
        }

        fn hangup(&mut self) {
            let mut s = self.0.lock().unwrap();
            s.carrier = false;
            s.hangups += 1;
        }

        fn listen(&mut self, addr: &str) -> io::Result<()> {
            self.0.lock().unwrap().listen_addr = Some(addr.to_string());
            Ok(())
        }

        fn ringing(&self) -> bool {
            self.0.lock().unwrap().ringing
        }

        fn answer(&mut self) -> bool {
            let mut s = self.0.lock().unwrap();
            if !s.ringing {
                return false;
            }
            s.ringing = false;
            if s.pending_dead {
                s.pending_dead = false;
                return false;
            }
            s.carrier = true;
            true
        }

        fn reject(&mut self) {
            let mut s = self.0.lock().unwrap();
            if s.ringing {
                s.ringing = false;
                s.reject_count += 1;
            }
        }
    }

    fn fake() -> (ModemSerialSink, Arc<Mutex<FakeState>>) {
        let state = Arc::new(Mutex::new(FakeState::default()));
        let sink = ModemSerialSink::with_transport(Box::new(FakeTransport(Arc::clone(&state))));
        (sink, state)
    }

    fn type_line(sink: &mut ModemSerialSink, s: &str, at_cck: u64) {
        for b in s.bytes() {
            sink.write_byte(b, at_cck);
        }
        sink.write_byte(0x0D, at_cck);
    }

    fn drain(sink: &mut ModemSerialSink) -> Vec<u8> {
        let mut v = Vec::new();
        while let Some(b) = sink.read_byte() {
            v.push(b);
        }
        v
    }

    fn drain_str(sink: &mut ModemSerialSink) -> String {
        String::from_utf8(drain(sink)).unwrap()
    }

    /// A fake-transport sink with echo already switched off, for tests
    /// that only care about result-code text, not the echoed command line.
    fn fake_no_echo() -> (ModemSerialSink, Arc<Mutex<FakeState>>) {
        let (mut sink, state) = fake();
        type_line(&mut sink, "ATE0", 0);
        drain(&mut sink);
        (sink, state)
    }

    // ---- 1. Command parsing ------------------------------------------

    #[test]
    fn bare_at_is_ok() {
        let (mut sink, _state) = fake();
        type_line(&mut sink, "AT", 0);
        let out = drain_str(&mut sink);
        assert!(out.ends_with("OK\r\n"), "{out:?}");
    }

    #[test]
    fn e0_disables_echo() {
        let (mut sink, _state) = fake();
        // Echo is on by default: the "ATE0\r" itself echoes back.
        type_line(&mut sink, "ATE0", 0);
        let out = drain_str(&mut sink);
        assert!(out.starts_with("ATE0\r"), "{out:?}");
        // Now echo is off: nothing but the result code comes back.
        type_line(&mut sink, "ATI0", 1);
        let out = drain_str(&mut sink);
        assert!(!out.contains("ATI0"), "{out:?}");
    }

    #[test]
    fn v0_gives_numeric_codes_v1_gives_verbose() {
        let (mut sink, _state) = fake_no_echo();
        type_line(&mut sink, "ATV0", 0);
        assert_eq!(drain_str(&mut sink), "0\r");
        type_line(&mut sink, "ATV1", 0);
        assert_eq!(drain_str(&mut sink), "\r\nOK\r\n");
    }

    #[test]
    fn q1_suppresses_all_result_codes() {
        let (mut sink, _state) = fake_no_echo();
        type_line(&mut sink, "ATQ1", 0);
        assert!(drain(&mut sink).is_empty());
        type_line(&mut sink, "AT", 0);
        assert!(drain(&mut sink).is_empty());
    }

    #[test]
    fn chained_commands_apply_left_to_right() {
        let (mut sink, _state) = fake_no_echo();
        type_line(&mut sink, "ATE0Q0V1", 0);
        // E0 took effect immediately (no echo of this line's tail, it was
        // already off), Q0 means results are not suppressed, V1 means
        // verbose OK.
        assert_eq!(drain_str(&mut sink), "\r\nOK\r\n");
    }

    #[test]
    fn garbage_line_is_error() {
        let (mut sink, _state) = fake_no_echo();
        type_line(&mut sink, "ATX", 0); // 'X' is not a recognized command
        let out = drain_str(&mut sink);
        assert!(out.ends_with("ERROR\r\n"), "{out:?}");
    }

    #[test]
    fn overlong_line_is_error_without_growth() {
        let (mut sink, _state) = fake_no_echo();
        sink.write_byte(b'A', 0);
        sink.write_byte(b'T', 0);
        // Fill the line buffer to exactly its cap; the next byte (still
        // short of a terminating CR) must trip the overflow guard rather
        // than grow the buffer past MAX_LINE_LEN.
        for _ in 0..(MAX_LINE_LEN - 2) {
            sink.write_byte(b'1', 0);
        }
        assert_eq!(sink.line.len(), MAX_LINE_LEN);
        sink.write_byte(b'1', 0);
        assert!(sink.line.is_empty());
        let out = drain_str(&mut sink);
        assert!(out.contains("ERROR"), "{out:?}");
    }

    // ---- 2. S-registers -----------------------------------------------

    #[test]
    fn s_register_defaults_and_writes() {
        let (mut sink, _state) = fake_no_echo();
        type_line(&mut sink, "ATS2?", 0);
        assert_eq!(drain_str(&mut sink), "\r\n43\r\n\r\nOK\r\n");

        type_line(&mut sink, "ATS2=36", 0);
        drain(&mut sink);
        type_line(&mut sink, "ATS2?", 0);
        assert_eq!(drain_str(&mut sink), "\r\n36\r\n\r\nOK\r\n");

        type_line(&mut sink, "ATS12=10", 0);
        drain(&mut sink);
        type_line(&mut sink, "ATS12?", 0);
        assert_eq!(drain_str(&mut sink), "\r\n10\r\n\r\nOK\r\n");

        type_line(&mut sink, "ATS99?", 0);
        assert_eq!(drain_str(&mut sink), "\r\n0\r\n\r\nOK\r\n");
        type_line(&mut sink, "ATS99=5", 0);
        assert_eq!(drain_str(&mut sink), "\r\nOK\r\n");
    }

    // ---- 3. Dial --------------------------------------------------------

    #[test]
    fn successful_dial_connects_and_relays() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATD127.0.0.1:2323", 0);
        assert_eq!(drain_str(&mut sink), "\r\nCONNECT\r\n");
        assert_eq!(
            state.lock().unwrap().dialed.as_deref(),
            Some("127.0.0.1:2323")
        );

        // Guest -> transport.
        sink.write_byte(b'x', 100);
        assert_eq!(state.lock().unwrap().from_guest, vec![b'x']);

        // Transport -> guest.
        state.lock().unwrap().to_guest.push_back(b'y');
        assert!(sink.has_pending_input());
        assert_eq!(sink.read_byte(), Some(b'y'));
    }

    #[test]
    fn refused_dial_reports_busy() {
        let (mut sink, state) = fake_no_echo();
        state.lock().unwrap().dial_result = Some(Err(DialError::Refused));
        type_line(&mut sink, "ATD127.0.0.1:2323", 0);
        assert_eq!(drain_str(&mut sink), "\r\nBUSY\r\n");
    }

    #[test]
    fn unreachable_dial_reports_no_carrier() {
        let (mut sink, state) = fake_no_echo();
        state.lock().unwrap().dial_result = Some(Err(DialError::Unreachable));
        type_line(&mut sink, "ATD127.0.0.1:2323", 0);
        assert_eq!(drain_str(&mut sink), "\r\nNO CARRIER\r\n");
    }

    #[test]
    fn atdt_variant_and_default_port() {
        let (mut sink, state) = fake();
        type_line(&mut sink, "ATDT127.0.0.1", 0);
        drain(&mut sink);
        assert_eq!(
            state.lock().unwrap().dialed.as_deref(),
            Some("127.0.0.1:23")
        );
    }

    // ---- 4. Escape guard ------------------------------------------------

    fn guard_ccks(s12: u8) -> u64 {
        u64::from(s12) * u64::from(PAULA_CLOCK_HZ) / 50
    }

    #[test]
    fn proper_escape_returns_to_command_mode_without_forwarding() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        let g = guard_ccks(50);
        let connect_cck = 0u64; // the CR of the ATD line
        let t0 = connect_cck + g + 1;
        sink.write_byte(b'+', t0);
        sink.write_byte(b'+', t0 + 10);
        sink.write_byte(b'+', t0 + 20);
        assert!(state.lock().unwrap().from_guest.is_empty());
        // Next event after the trailing guard elapses completes the escape;
        // that event is itself processed in command mode.
        sink.write_byte(0x0D, t0 + 20 + g + 1);
        let out = drain_str(&mut sink);
        assert!(out.contains("OK"), "{out:?}");
        assert!(state.lock().unwrap().from_guest.is_empty());
        // ATO proves we are back online with carrier intact.
        type_line(&mut sink, "ATO", t0 + 20 + g + 1);
        assert_eq!(drain_str(&mut sink), "\r\nCONNECT\r\n");
    }

    #[test]
    fn short_leading_guard_forwards_escape_chars() {
        let (mut sink, state) = fake();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        // Immediately after CONNECT: no lead silence at all.
        sink.write_byte(b'+', 1);
        sink.write_byte(b'+', 2);
        sink.write_byte(b'+', 3);
        assert_eq!(state.lock().unwrap().from_guest, vec![b'+', b'+', b'+']);
    }

    #[test]
    fn plus_plus_plus_embedded_in_traffic_is_forwarded() {
        let (mut sink, state) = fake();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        let g = guard_ccks(50);
        sink.write_byte(b'X', 0);
        // Not enough silence after 'X' before the '+' run starts.
        sink.write_byte(b'+', g / 2);
        sink.write_byte(b'+', g / 2 + 10);
        sink.write_byte(b'+', g / 2 + 20);
        assert_eq!(
            state.lock().unwrap().from_guest,
            vec![b'X', b'+', b'+', b'+']
        );
    }

    #[test]
    fn four_escape_chars_are_forwarded() {
        let (mut sink, state) = fake();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        let g = guard_ccks(50);
        let t0 = g + 1;
        sink.write_byte(b'+', t0);
        sink.write_byte(b'+', t0 + 10);
        sink.write_byte(b'+', t0 + 20);
        // A fourth '+' arrives before the trailing guard elapses: break.
        sink.write_byte(b'+', t0 + 30);
        assert_eq!(
            state.lock().unwrap().from_guest,
            vec![b'+', b'+', b'+', b'+']
        );
    }

    #[test]
    fn escape_char_honours_s2_change() {
        let (mut sink, state) = fake();
        type_line(&mut sink, "ATS2=36", 0);
        drain(&mut sink);
        type_line(&mut sink, "ATD127.0.0.1:23", 1);
        drain(&mut sink);
        let g = guard_ccks(50);
        let t0 = 1 + g + 1;
        // Old escape char '+' no longer triggers anything.
        sink.write_byte(b'+', t0);
        sink.write_byte(b'+', t0 + 10);
        sink.write_byte(b'+', t0 + 20);
        assert_eq!(state.lock().unwrap().from_guest, vec![b'+', b'+', b'+']);
        state.lock().unwrap().from_guest.clear();
        // The new escape char '$' (36) does.
        let t1 = t0 + 20 + g + 1;
        sink.write_byte(36, t1);
        sink.write_byte(36, t1 + 10);
        sink.write_byte(36, t1 + 20);
        assert!(state.lock().unwrap().from_guest.is_empty());
    }

    #[test]
    fn stale_pending_escape_restarts_as_new_candidate() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        let g = guard_ccks(50);
        let t0 = g + 1;
        // A single '+' after a valid lead guard opens a pending candidate.
        sink.write_byte(b'+', t0);
        // Then a gap longer than the guard: the withheld '+' is itself
        // stale guest-line silence now, so it forwards and the next S2
        // byte starts a fresh candidate rather than busting to a forward.
        let t1 = t0 + g + 5;
        sink.write_byte(b'+', t1);
        assert_eq!(state.lock().unwrap().from_guest, vec![b'+']);
        state.lock().unwrap().from_guest.clear();
        // A correctly timed "+++" from t1 completes the escape...
        sink.write_byte(b'+', t1 + 10);
        sink.write_byte(b'+', t1 + 20);
        assert!(state.lock().unwrap().from_guest.is_empty());
        // ...and the trailing guard drops to command mode.
        let t2 = t1 + 20 + g + 1;
        sink.write_byte(0x0D, t2);
        let out = drain_str(&mut sink);
        assert!(out.contains("OK"), "{out:?}");
        assert!(state.lock().unwrap().from_guest.is_empty());
        // ATO proves we are back online with carrier intact.
        type_line(&mut sink, "ATO", t2);
        assert_eq!(drain_str(&mut sink), "\r\nCONNECT\r\n");
    }

    // ---- 5. ATH / ATO after escape --------------------------------------

    #[test]
    fn ath_after_escape_hangs_up_and_deasserts_cd() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        let g = guard_ccks(50);
        let t0 = g + 1;
        sink.write_byte(b'+', t0);
        sink.write_byte(b'+', t0 + 10);
        sink.write_byte(b'+', t0 + 20);
        sink.write_byte(0x0D, t0 + 20 + g + 1);
        drain(&mut sink);
        type_line(&mut sink, "ATH", t0 + 20 + g + 1);
        assert_eq!(drain_str(&mut sink), "\r\nOK\r\n");
        assert_eq!(state.lock().unwrap().hangups, 1);
        assert_eq!(sink.control_lines(), Some(1 << 5));
    }

    #[test]
    fn ato_after_escape_returns_online() {
        let (mut sink, _state) = fake_no_echo();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        let g = guard_ccks(50);
        let t0 = g + 1;
        sink.write_byte(b'+', t0);
        sink.write_byte(b'+', t0 + 10);
        sink.write_byte(b'+', t0 + 20);
        sink.write_byte(0x0D, t0 + 20 + g + 1);
        drain(&mut sink);
        type_line(&mut sink, "ATO", t0 + 20 + g + 1);
        assert_eq!(drain_str(&mut sink), "\r\nCONNECT\r\n");
    }

    // ---- 6. Control lines -------------------------------------------------

    #[test]
    fn control_lines_polarity_with_c1_default() {
        let (mut sink, state) = fake();
        // Idle, no call: /CD deasserted (bit 5 = 1), /DSR and /CTS asserted.
        assert_eq!(sink.control_lines(), Some(1 << 5));
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        assert_eq!(sink.control_lines(), Some(0));
        state.lock().unwrap().carrier = false;
        assert_eq!(sink.control_lines(), Some(1 << 5));
    }

    #[test]
    fn control_lines_always_asserted_with_c0() {
        let (mut sink, _state) = fake();
        type_line(&mut sink, "AT&C0", 0);
        drain(&mut sink);
        assert_eq!(sink.control_lines(), Some(0));
    }

    // ---- 7. DTR drop ------------------------------------------------------

    #[test]
    fn dtr_drop_with_default_d2_hangs_up() {
        let (mut sink, state) = fake();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        sink.set_control_outputs(true, false);
        sink.set_control_outputs(false, false);
        assert_eq!(state.lock().unwrap().hangups, 1);
        assert!(drain_str(&mut sink).contains("NO CARRIER"));
    }

    #[test]
    fn dtr_drop_with_d0_is_ignored() {
        let (mut sink, state) = fake();
        type_line(&mut sink, "AT&D0", 0);
        drain(&mut sink);
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        sink.set_control_outputs(true, false);
        sink.set_control_outputs(false, false);
        assert_eq!(state.lock().unwrap().hangups, 0);
    }

    // ---- 8. CONNECT rate --------------------------------------------------

    #[test]
    fn connect_reports_last_baud() {
        let (mut sink, _state) = fake_no_echo();
        sink.baud_changed(9600);
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        assert_eq!(drain_str(&mut sink), "\r\nCONNECT 9600\r\n");
    }

    // ---- 9. Remote close ----------------------------------------------

    #[test]
    fn remote_close_during_online_reports_no_carrier() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        state.lock().unwrap().carrier = false;
        assert!(sink.has_pending_input());
        assert_eq!(drain_str(&mut sink), "\r\nNO CARRIER\r\n");
        // Back in command mode: AT still works.
        type_line(&mut sink, "AT", 0);
        assert_eq!(drain_str(&mut sink), "\r\nOK\r\n");
    }

    // ---- 10. Inbound calls -------------------------------------------------

    const RING_CADENCE: u64 = 4 * PAULA_CLOCK_HZ as u64;

    #[test]
    fn ring_cadence_and_s1_counting() {
        let (mut sink, state) = fake_no_echo();
        state.lock().unwrap().ringing = true;
        sink.poll(0);
        assert_eq!(drain_str(&mut sink), "\r\nRING\r\n");
        // Too soon for a second ring.
        sink.poll(RING_CADENCE - 1);
        assert!(drain(&mut sink).is_empty());
        sink.poll(RING_CADENCE);
        assert_eq!(drain_str(&mut sink), "\r\nRING\r\n");

        type_line(&mut sink, "ATS1?", RING_CADENCE);
        assert_eq!(drain_str(&mut sink), "\r\n2\r\n\r\nOK\r\n");
    }

    #[test]
    fn ata_answers_and_reports_connect() {
        let (mut sink, state) = fake_no_echo();
        state.lock().unwrap().ringing = true;
        sink.poll(0);
        drain(&mut sink);
        type_line(&mut sink, "ATA", 0);
        assert_eq!(drain_str(&mut sink), "\r\nCONNECT\r\n");
        assert!(state.lock().unwrap().carrier);
        assert_eq!(sink.control_lines(), Some(0));
    }

    #[test]
    fn ata_with_no_caller_reports_no_carrier() {
        let (mut sink, _state) = fake_no_echo();
        type_line(&mut sink, "ATA", 0);
        assert_eq!(drain_str(&mut sink), "\r\nNO CARRIER\r\n");
    }

    #[test]
    fn s0_auto_answers_on_the_nth_ring() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATS0=2", 0);
        drain(&mut sink);
        state.lock().unwrap().ringing = true;
        sink.poll(0); // ring 1
        assert_eq!(drain_str(&mut sink), "\r\nRING\r\n");
        sink.poll(RING_CADENCE); // ring 2: S1 reaches S0, auto-answers
        assert_eq!(drain_str(&mut sink), "\r\nRING\r\n\r\nCONNECT\r\n");
        assert!(state.lock().unwrap().carrier);
    }

    #[test]
    fn unanswered_caller_is_rejected_after_ten_rings() {
        let (mut sink, state) = fake_no_echo();
        state.lock().unwrap().ringing = true;
        let mut cck = 0u64;
        for _ in 0..10 {
            sink.poll(cck);
            drain(&mut sink);
            cck += RING_CADENCE;
        }
        assert_eq!(state.lock().unwrap().reject_count, 1);
        assert!(!state.lock().unwrap().ringing);
    }

    #[test]
    fn ring_text_honours_v0_and_q1() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATV0", 0);
        drain(&mut sink);
        state.lock().unwrap().ringing = true;
        sink.poll(0);
        assert_eq!(drain_str(&mut sink), "2\r");

        type_line(&mut sink, "ATV1Q1", 0);
        drain(&mut sink);
        state.lock().unwrap().ringing = true;
        sink.poll(RING_CADENCE * 10); // a fresh ring, well past the cadence
        assert!(drain(&mut sink).is_empty());
    }

    // ---- 11. Escape completion / NO CARRIER via poll -----------------------

    #[test]
    fn escape_completes_via_poll_with_no_guest_byte() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        let g = guard_ccks(50);
        let t0 = g + 1;
        sink.write_byte(b'+', t0);
        sink.write_byte(b'+', t0 + 10);
        sink.write_byte(b'+', t0 + 20);
        assert!(state.lock().unwrap().from_guest.is_empty());
        // No further guest byte at all -- poll alone, once the trailing
        // guard has elapsed, completes the escape.
        sink.poll(t0 + 20 + g + 1);
        assert_eq!(drain_str(&mut sink), "\r\nOK\r\n");
        type_line(&mut sink, "ATO", t0 + 20 + g + 1);
        assert_eq!(drain_str(&mut sink), "\r\nCONNECT\r\n");
    }

    #[test]
    fn no_carrier_surfaced_in_command_mode_after_escape() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        let g = guard_ccks(50);
        let t0 = g + 1;
        sink.write_byte(b'+', t0);
        sink.write_byte(b'+', t0 + 10);
        sink.write_byte(b'+', t0 + 20);
        sink.poll(t0 + 20 + g + 1);
        drain(&mut sink);
        // Remote drops while parked in command mode: nothing else polls
        // the transport while idle there, so this is the only place that
        // notices.
        state.lock().unwrap().carrier = false;
        sink.poll(t0 + 20 + g + 2);
        assert_eq!(drain_str(&mut sink), "\r\nNO CARRIER\r\n");
        // Reported once, not on every subsequent poll.
        sink.poll(t0 + 20 + g + 3);
        assert!(drain(&mut sink).is_empty());
    }

    #[test]
    fn atd_with_a_call_up_hangs_up_first() {
        let (mut sink, state) = fake_no_echo();
        type_line(&mut sink, "ATD127.0.0.1:23", 0);
        drain(&mut sink);
        let g = guard_ccks(50);
        let t0 = g + 1;
        sink.write_byte(b'+', t0);
        sink.write_byte(b'+', t0 + 10);
        sink.write_byte(b'+', t0 + 20);
        sink.poll(t0 + 20 + g + 1);
        drain(&mut sink);
        assert_eq!(state.lock().unwrap().hangups, 0);
        type_line(&mut sink, "ATD127.0.0.1:24", t0 + 20 + g + 1);
        assert_eq!(drain_str(&mut sink), "\r\nCONNECT\r\n");
        assert_eq!(state.lock().unwrap().hangups, 1);
        assert_eq!(
            state.lock().unwrap().dialed.as_deref(),
            Some("127.0.0.1:24")
        );
    }

    // ---- Real TCP tests ---------------------------------------------------

    #[test]
    fn tcp_dial_connects_and_relays_both_directions() {
        let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        let accepted = thread::spawn(move || listener.accept().unwrap().0);
        let mut sink = ModemSerialSink::with_transport(Box::new(TcpModemTransport::new()));
        type_line(&mut sink, &format!("ATD{addr}"), 0);
        let mut peer = accepted.join().unwrap();
        let out = drain_str(&mut sink);
        assert!(out.contains("CONNECT"), "{out:?}");

        sink.write_byte(b'A', 1);
        let mut got = [0u8; 1];
        peer.set_read_timeout(Some(Duration::from_secs(5))).unwrap();
        peer.read_exact(&mut got).unwrap();
        assert_eq!(&got, b"A");

        peer.write_all(b"B").unwrap();
        let deadline = Instant::now() + Duration::from_secs(5);
        let mut got_b = None;
        while Instant::now() < deadline {
            if let Some(b) = sink.read_byte() {
                got_b = Some(b);
                break;
            }
            thread::yield_now();
        }
        assert_eq!(got_b, Some(b'B'));

        drop(peer);
        let deadline = Instant::now() + Duration::from_secs(5);
        let mut out = Vec::new();
        loop {
            assert!(Instant::now() < deadline, "NO CARRIER never arrived");
            if let Some(b) = sink.read_byte() {
                out.push(b);
                if out.ends_with(b"NO CARRIER\r\n") {
                    break;
                }
            } else {
                thread::yield_now();
            }
        }
    }

    #[test]
    fn tcp_dial_refused_reports_busy() {
        let addr = {
            let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
            listener.local_addr().unwrap()
        };
        let mut sink = ModemSerialSink::with_transport(Box::new(TcpModemTransport::new()));
        type_line(&mut sink, &format!("ATD{addr}"), 0);
        let out = drain_str(&mut sink);
        assert!(out.contains("BUSY"), "{out:?}");
    }

    #[test]
    fn two_modems_talk_over_real_tcp() {
        let mut answering_transport = TcpModemTransport::new();
        answering_transport.listen("127.0.0.1:0").unwrap();
        let addr = answering_transport.listen_addr().unwrap();
        let mut answering = ModemSerialSink::with_transport(Box::new(answering_transport));
        let mut dialing = ModemSerialSink::with_transport(Box::new(TcpModemTransport::new()));

        type_line(&mut dialing, &format!("ATD{addr}"), 0);
        let out = drain_str(&mut dialing);
        assert!(out.contains("CONNECT"), "{out:?}");

        // Wait for the caller to reach the listener thread and for a poll
        // (Paula's job in production) to notice and send RING.
        let deadline = Instant::now() + Duration::from_secs(5);
        let mut cck = 0u64;
        let mut saw_ring = false;
        while Instant::now() < deadline {
            answering.poll(cck);
            if drain_str(&mut answering).contains("RING") {
                saw_ring = true;
                break;
            }
            cck += 1;
            thread::yield_now();
        }
        assert!(saw_ring, "answering side never saw RING");

        type_line(&mut answering, "ATA", cck);
        let out = drain_str(&mut answering);
        assert!(out.contains("CONNECT"), "{out:?}");

        assert_eq!(dialing.control_lines(), Some(0));
        assert_eq!(answering.control_lines(), Some(0));

        dialing.write_byte(b'Q', 100);
        let deadline = Instant::now() + Duration::from_secs(5);
        let mut got = None;
        while Instant::now() < deadline {
            if let Some(b) = answering.read_byte() {
                got = Some(b);
                break;
            }
            thread::yield_now();
        }
        assert_eq!(got, Some(b'Q'));

        answering.write_byte(b'R', 100);
        let deadline = Instant::now() + Duration::from_secs(5);
        let mut got = None;
        while Instant::now() < deadline {
            if let Some(b) = dialing.read_byte() {
                got = Some(b);
                break;
            }
            thread::yield_now();
        }
        assert_eq!(got, Some(b'R'));
    }
}
