// SPDX-License-Identifier: GPL-3.0-or-later

//! Default-CI half of copperhf.device's M6 integration matrix
//! (`COPPERHF-DEVICE-PLAN.md`'s "M6 -- Tests, CI, docs"): the synthetic
//! FFS-from-LSEG stand-in that needs no licensed assets, exercising
//! `guest/copperhf/mounter.c`'s FSHD/LSEG loader (`chf_find_or_load_
//! filesystem`/`chf_load_lseg_chain`) against a hand-crafted RDB image
//! whose exact block layout is dictated by the guest-side probe this test
//! drives -- see `guest/copperhf-test/chftest_m6.c`'s own header comment
//! for the full image contract this file builds to. The real-Kickstart
//! matrix axes ({RDB, RDB-less} x {OFS, FFS-from-LSEG, PFS3-DS >4 GiB} x
//! {1.3, 3.1, 3.2}) live in `tests/copperhf_kickstarts.rs`, `#[ignore]`d
//! behind local ROM/filesystem-binary assets; this file is the one piece
//! of the M6 matrix that runs on every checkout, in default CI, like
//! `tests/copperhf_device.rs`/`tests/copperhf_m4_guest.rs` before it.
//!
//! `guest/copperhf-test/lsegfix` (generated by the adjacent
//! `gen_lsegfix.py`, both committed) is a minimal, hand-crafted three-hunk
//! LoadSeg-able binary carrying its own relocation self-test (its entry
//! point XORs together a plain constant, a round-tripped cross-hunk
//! data->bss pointer write/read, and a cross-hunk data->code pointer read,
//! and only returns the expected magic if every relocation actually
//! landed); the guest probe verifies FileSystem.resource, the loaded
//! seglist's segment count, calling that entry point, and the resulting
//! DeviceNode's patched fields -- four independent markers, one block
//! each, read back the same way `tests/copperhf_m4_guest.rs` reads its own
//! subtest markers.
//!
//! Needs no local assets at all: the bundled AROS ROM boots the `--run`
//! staging volume. Release-only, like every other AROS-boot integration
//! test in this suite: a debug-build emulator is far too slow for a full
//! AROS boot plus `--run` staging.

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

const SECTOR_SIZE: usize = 512;
/// One 256 KiB cylinder of RDB/FSHD/LSEG header, matching `RDB_HEADS`/
/// `RDB_SPT` (16 x 32) used throughout this suite's other hand-built RDB
/// images -- and, per `chftest_m6.c`'s contract, exactly where the fixture
/// draws the line between "header cylinder" (blocks 0..511) and "partition
/// cylinder" (block 512 on).
const CYL_SECTORS: u32 = 16 * 32;
const CYL_BYTES: u64 = CYL_SECTORS as u64 * SECTOR_SIZE as u64;

// --- exact values from guest/copperhf-test/chftest_m6.c's image contract --

const TEST_DOSTYPE: u32 = 0x5453_5401; // 'TST\1'
const TEST_FSVERSION: u32 = 0x0001_000A; // 1.10
const TEST_PATCHFLAGS: u32 = 0x180; // FSE_PF_SEGLIST | FSE_PF_GLOBALVEC
const TEST_GLOBALVEC: u32 = 0xFFFF_FFFF; // -1

// Marker blocks (partition cylinder, block-512-relative offsets in the
// probe's own source; here addressed as absolute image blocks, since this
// test reads the fixture's raw bytes rather than mounting a filesystem).
const BLK_FSR: u64 = 512;
const BLK_SEGCHAIN: u64 = 513;
const BLK_EXEC: u64 = 514;
const BLK_DEVNODE: u64 = 515;

struct Subtest {
    block: u64,
    name: &'static str,
    ok_marker: &'static str,
    bad_marker: &'static str,
}

const SUBTESTS: &[Subtest] = &[
    Subtest {
        block: BLK_FSR,
        name: "FileSystem.resource entry (fse_Version/fse_PatchFlags)",
        ok_marker: "M6-FSR-OK",
        bad_marker: "M6-FSR-BAD",
    },
    Subtest {
        block: BLK_SEGCHAIN,
        name: "loaded seglist chain length",
        ok_marker: "M6-SEGCHAIN-OK",
        bad_marker: "M6-SEGCHAIN-BAD",
    },
    Subtest {
        block: BLK_EXEC,
        name: "seglist entry point relocation self-test",
        ok_marker: "M6-EXEC-OK",
        bad_marker: "M6-EXEC-BAD",
    },
    Subtest {
        block: BLK_DEVNODE,
        name: "DeviceNode dn_SegList/dn_GlobalVec patch",
        ok_marker: "M6-DEVNODE-OK",
        bad_marker: "M6-DEVNODE-BAD",
    },
];

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn tail(text: &[u8], line_count: usize) -> String {
    let text = String::from_utf8_lossy(text);
    let lines = text.lines().collect::<Vec<_>>();
    lines[lines.len().saturating_sub(line_count)..].join("\n")
}

fn toml_path(path: &Path) -> String {
    format!("'{}'", path.display())
}

fn put_be32(block: &mut [u8], offset: usize, value: u32) {
    block[offset..offset + 4].copy_from_slice(&value.to_be_bytes());
}

/// Sum-to-zero longword checksum shared by every RDB-family block
/// (`devices/hardblocks.h`): the checksum field (offset 8) is zeroed, the
/// first `summed_longs` big-endian longs are summed with wrapping add, and
/// the checksum is the value that makes that sum zero.
fn rdb_checksum(block: &mut [u8], summed_longs: usize) {
    put_be32(block, 8, 0);
    let mut sum = 0u32;
    for i in 0..summed_longs {
        sum = sum.wrapping_add(u32::from_be_bytes(
            block[i * 4..i * 4 + 4].try_into().unwrap(),
        ));
    }
    put_be32(block, 8, 0u32.wrapping_sub(sum));
}

fn build_rdsk_block() -> Vec<u8> {
    let mut b = vec![0u8; SECTOR_SIZE];
    b[0..4].copy_from_slice(b"RDSK");
    put_be32(&mut b, 4, 64); // rdb_SummedLongs
    put_be32(&mut b, 12, 7); // rdb_HostID
    put_be32(&mut b, 16, SECTOR_SIZE as u32); // rdb_BlockBytes
    put_be32(&mut b, 20, 0x17); // rdb_Flags
    put_be32(&mut b, 24, !0); // rdb_BadBlockList
    put_be32(&mut b, 28, 1); // rdb_PartitionList
    put_be32(&mut b, 32, 2); // rdb_FileSysHeaderList
    put_be32(&mut b, 36, !0);
    put_be32(&mut b, 40, !0);
    for off in (44..64).step_by(4) {
        put_be32(&mut b, off, !0);
    }
    put_be32(&mut b, 64, 2); // rdb_Cylinders: header cylinder + one partition cylinder
    put_be32(&mut b, 68, 32); // rdb_Sectors
    put_be32(&mut b, 72, 16); // rdb_Heads
    put_be32(&mut b, 76, 1); // rdb_Interleave
    put_be32(&mut b, 80, 2); // rdb_Park
    put_be32(&mut b, 96, !0);
    put_be32(&mut b, 100, !0);
    put_be32(&mut b, 104, 3);
    put_be32(&mut b, 128, 0); // rdb_RDBBlocksLo
    put_be32(&mut b, 132, CYL_SECTORS - 1); // rdb_RDBBlocksHi
    put_be32(&mut b, 136, 1); // rdb_LoCylinder
    put_be32(&mut b, 140, 1); // rdb_HiCylinder: partition spans cylinder 1 only
    put_be32(&mut b, 144, CYL_SECTORS); // rdb_CylBlocks
    rdb_checksum(&mut b, 64);
    b
}

/// `PBFF_BOOTABLE` clear (this fixture must *mount*, not autoboot -- the
/// probe arrives via ordinary `--run` staging, not from this unit) and
/// `PBFF_NOMOUNT` clear (it must still be mounted).
fn build_part_block() -> Vec<u8> {
    let mut b = vec![0u8; SECTOR_SIZE];
    b[0..4].copy_from_slice(b"PART");
    put_be32(&mut b, 4, 64);
    put_be32(&mut b, 12, 7);
    put_be32(&mut b, 16, !0); // pb_Next: none
    put_be32(&mut b, 20, 0); // pb_Flags: neither BOOTABLE nor NOMOUNT
    let name = b"CHFM6";
    b[36] = name.len() as u8;
    b[37..37 + name.len()].copy_from_slice(name);
    let env: [u32; 17] = [
        16,
        (SECTOR_SIZE / 4) as u32,
        0,
        16,
        1,
        32,
        2,
        0,
        0,
        1, // low cylinder
        1, // high cylinder: cylinder 1 only
        30,
        0,
        0x00FF_FFFF,
        0x7FFF_FFFE,
        0, // boot priority: irrelevant, not bootable
        TEST_DOSTYPE,
    ];
    for (i, v) in env.iter().enumerate() {
        put_be32(&mut b, 128 + i * 4, *v);
    }
    rdb_checksum(&mut b, 64);
    b
}

fn build_fshd_block() -> Vec<u8> {
    let mut b = vec![0u8; SECTOR_SIZE];
    b[0..4].copy_from_slice(b"FSHD");
    put_be32(&mut b, 4, 64);
    put_be32(&mut b, 12, 7);
    put_be32(&mut b, 16, !0); // fhb_Next: only FSHD on the list
    put_be32(&mut b, 20, 0); // fhb_Flags
    put_be32(&mut b, 32, TEST_DOSTYPE);
    put_be32(&mut b, 36, TEST_FSVERSION);
    put_be32(&mut b, 40, TEST_PATCHFLAGS);
    put_be32(&mut b, 44, 0); // fhb_Type
    put_be32(&mut b, 48, 0); // fhb_Task
    put_be32(&mut b, 52, 0); // fhb_Lock
    put_be32(&mut b, 56, 0); // fhb_Handler
    put_be32(&mut b, 60, 0x2000); // fhb_StackSize
    put_be32(&mut b, 64, 0); // fhb_Priority
    put_be32(&mut b, 68, 0); // fhb_Startup
    put_be32(&mut b, 72, 3); // fhb_SegListBlocks: block 3
    put_be32(&mut b, 76, TEST_GLOBALVEC);
    rdb_checksum(&mut b, 64);
    b
}

/// A single `LoadSegBlock` at block 3, carrying `guest/copperhf-test/
/// lsegfix`'s bytes verbatim, zero-padded to the 492-byte payload;
/// `lsb_Next = -1` since the fixture (248 bytes as of this writing --
/// see the assert below, which is the actual guard, not this comment)
/// fits in one block.
fn build_lseg_block(fixture: &[u8]) -> Vec<u8> {
    assert!(
        fixture.len() <= 492,
        "lsegfix ({} bytes) no longer fits in one LoadSegBlock -- chftest_m6.c's \
         contract assumes a single-block chain",
        fixture.len()
    );
    let mut b = vec![0u8; SECTOR_SIZE];
    b[0..4].copy_from_slice(b"LSEG");
    put_be32(&mut b, 4, 128); // lsb_SummedLongs: whole block
    put_be32(&mut b, 12, 7); // lsb_HostID
    put_be32(&mut b, 16, !0); // lsb_Next: chain ends here
    b[20..20 + fixture.len()].copy_from_slice(fixture);
    rdb_checksum(&mut b, 128);
    b
}

fn build_fixture_image() -> Vec<u8> {
    let fixture = std::fs::read(repo_root().join("guest/copperhf-test/lsegfix"))
        .expect("read guest/copperhf-test/lsegfix (committed fixture binary)");

    let mut header = vec![0u8; CYL_BYTES as usize];
    header[..SECTOR_SIZE].copy_from_slice(&build_rdsk_block());
    header[SECTOR_SIZE..2 * SECTOR_SIZE].copy_from_slice(&build_part_block());
    header[2 * SECTOR_SIZE..3 * SECTOR_SIZE].copy_from_slice(&build_fshd_block());
    header[3 * SECTOR_SIZE..4 * SECTOR_SIZE].copy_from_slice(&build_lseg_block(&fixture));

    let mut image = header;
    // Partition cylinder: no filesystem content at all (chftest_m6.c's
    // contract -- nothing ever reads through the mounted handler), just
    // zeroed space the probe writes its four markers into directly.
    image.extend(vec![0u8; CYL_BYTES as usize]);
    image
}

fn read_marker(image: &[u8], block: u64) -> Vec<u8> {
    let base = block as usize * SECTOR_SIZE;
    image[base..base + SECTOR_SIZE].to_vec()
}

#[test]
fn lseg_filesystem_loads_into_filesystem_resource() -> Result<(), Box<dyn std::error::Error>> {
    if cfg!(debug_assertions) {
        eprintln!(
            "skipping copperhf.device M6 LSEG-loader probe; run with --release \
             (a debug emulator is far too slow for a full AROS boot + --run staging)"
        );
        return Ok(());
    }

    let root = repo_root();
    let scratch =
        std::env::temp_dir().join(format!("copperline-copperhf-m6-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&scratch);
    let program_dir = scratch.join("program");
    let config_home = scratch.join("config-home");
    std::fs::create_dir_all(&program_dir)?;
    std::fs::create_dir_all(&config_home)?;

    let probe = program_dir.join("chftest_m6");
    std::fs::copy(root.join("guest/copperhf-test/chftest_m6"), &probe)?;

    let image_path = scratch.join("unit0.hdf");
    std::fs::File::create(&image_path)?.write_all(&build_fixture_image())?;

    let config = scratch.join("copperhf.toml");
    std::fs::write(
        &config,
        format!(
            "rom = \"<bundled-aros>\"\n\n[copperhf]\nunit0 = {}\n",
            toml_path(&image_path)
        ),
    )?;

    let screenshot = scratch.join("copperhf-m6.png");
    let output = Command::new(env!("CARGO_BIN_EXE_copperline"))
        .current_dir(&root)
        .env("RUST_LOG", "copperline=warn")
        .env("COPPERLINE_AROS_DIR", root.join("assets/aros"))
        .env("XDG_CONFIG_HOME", &config_home)
        .arg("--factory")
        .arg("--config")
        .arg(&config)
        .arg("--noaudio")
        .arg("--run")
        .arg(&probe)
        // Same emulated-time budget as tests/copperhf_m4_guest.rs's probe:
        // bundled-AROS `--run` boots hand the guest control at ~11s
        // emulated, and this probe (four in-memory checks, no I/O beyond
        // its own marker writes) finishes moments later.
        .arg("--screenshot-after")
        .arg("50")
        .arg(&screenshot)
        .output()?;
    assert!(
        output.status.success(),
        "Copperline exited with {}\nstdout:\n{}\nstderr:\n{}",
        output.status,
        tail(&output.stdout, 40),
        tail(&output.stderr, 80),
    );

    let bytes = std::fs::read(&image_path)?;
    for subtest in SUBTESTS {
        let marker = read_marker(&bytes, subtest.block);
        if marker.starts_with(subtest.bad_marker.as_bytes()) {
            panic!(
                "[{}] FAILED (block {}):\nstdout:\n{}\nstderr:\n{}",
                subtest.name,
                subtest.block,
                tail(&output.stdout, 40),
                tail(&output.stderr, 80),
            );
        }
        assert!(
            marker.starts_with(subtest.ok_marker.as_bytes()),
            "[{}] marker absent from block {} -- the probe never ran or never reached \
             this subtest (block read back {:?}):\nstdout:\n{}\nstderr:\n{}",
            subtest.name,
            subtest.block,
            &marker[..subtest.ok_marker.len().max(marker.len().min(32))],
            tail(&output.stdout, 40),
            tail(&output.stderr, 80),
        );
    }

    std::fs::remove_dir_all(&scratch)?;
    Ok(())
}
